#!/usr/bin/env ruby
# © 2012 Ruben Verborgh - Multimedia Lab

if ARGV == ['--help']
  puts "Outputs concepts, prefLabels, and non-interfering altLabels."
  puts "usage: uniquify_labels [SKOS concept hierarchy in Turtle format]"
  Kernel.exit
end

prefixes = { :skos => "<http://www.w3.org/2004/02/skos/core#>" }
concepts = {} # concept URIs indexed by label
altLabels = {}
subdivisions = {}

# read lines
ARGF.each do |line|
    case line
    # store prefixes
    when /^@prefix\s+(\w+):\s*(<.*>)\s*\./
      prefixes[$~[1]] = $~[2]
      
    # store prefLabels
    when /^(<.*?>) <http:\/\/www.w3.org\/2004\/02\/skos\/core#prefLabel> "(.*)"@[eE][Nn]\s*[.;]/,
         /^([^ ]+) skos:prefLabel "(.*)"@en\s*[.;]/
      (concepts[$~[2]] ||= []).push $~[1]
    
    # store altLabels
    when /^(<.*?>) <http:\/\/www.w3.org\/2004\/02\/skos\/core#altLabel> "(.*)"@[eE][Nn]\s*[.;]/,
         /^([^ ]+) skos:altLabel "(.*)"@en\s*[.;]/
      (altLabels[$~[1]] ||= []).push $~[2]
    
    # find subdivisions
    when /^(<.*?>) <http:\/\/www.w3.org\/2004\/02\/skos\/core#inScheme> .*#generalSubdivision>.$/,
         /^(<.*?>) <http:\/\/www.w3.org\/2004\/02\/skos\/core#member> .*\/collection_Subdivisions>\s*.$/
      subdivisions[$~[1]] = true
    end
end

# write prefixes
prefixes.each do |prefix, value|
  puts "@prefix #{prefix}: #{value}."
end

# write concepts
concepts.keys.sort.each do |label|
  conceptList = concepts[label]
  
  # split subdivisions apart
  concepts_in_subdivisions    = conceptList.find_all { |c|  subdivisions[c] }
  concept_not_in_subdivisions = conceptList.find_all { |c| !subdivisions[c] }
  
  # it's not a concept if there are many with the same label
  next if concept_not_in_subdivisions.length > 1
  
  # subdivisions have lowest priority
  concept = concept_not_in_subdivisions.first || concepts_in_subdivisions.first
  
  puts %Q{#{concept} a skos:Concept.}
  puts %Q{#{concept} skos:prefLabel "#{label}".}
  
  (altLabels[concept] || []).each do |altLabel|
    puts %Q{#{concept} skos:altLabel "#{altLabel}".} unless concepts[altLabel]
  end
end
